/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    AppContent: typeof import('./src/components/AppContent.vue')['default']
    AppearanceTabs: typeof import('./src/components/AppearanceTabs.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AppLogoIcon: typeof import('./src/components/AppLogoIcon.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppSidebarHeader: typeof import('./src/components/AppSidebarHeader.vue')['default']
    Badge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    Button: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    Card: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    Chart: typeof import('./src/components/Chart/Chart.vue')['default']
    ChartArea: typeof import('./src/components/Chart/ChartArea.vue')['default']
    ChartBar: typeof import('./src/components/Chart/ChartBar.vue')['default']
    ChartDoughnut: typeof import('./src/components/Chart/ChartDoughnut.vue')['default']
    ChartLine: typeof import('./src/components/Chart/ChartLine.vue')['default']
    ChartPie: typeof import('./src/components/Chart/ChartPie.vue')['default']
    Command: typeof import('./src/components/Command/Command.vue')['default']
    CommandModal: typeof import('./src/components/Command/CommandModal.vue')['default']
    DeleteUser: typeof import('./src/components/DeleteUser.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    HeadingSmall: typeof import('./src/components/HeadingSmall.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Input: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    InputError: typeof import('./src/components/InputError.vue')['default']
    Kanban: typeof import('./src/components/Kanban/Kanban.vue')['default']
    KanbanCard: typeof import('./src/components/Kanban/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./src/components/Kanban/KanbanColumn.vue')['default']
    KanbanColumnCards: typeof import('./src/components/Kanban/KanbanColumnCards.vue')['default']
    KanbanColumnFooter: typeof import('./src/components/Kanban/KanbanColumnFooter.vue')['default']
    KanbanColumnHeader: typeof import('./src/components/Kanban/KanbanColumnHeader.vue')['default']
    Label: typeof import('./src/components/Label.vue')['default']
    NavFooter: typeof import('./src/components/NavFooter.vue')['default']
    NavMain: typeof import('./src/components/NavMain.vue')['default']
    NavUser: typeof import('./src/components/NavUser.vue')['default']
    PlaceholderPattern: typeof import('./src/components/PlaceholderPattern.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    TextLink: typeof import('./src/components/TextLink.vue')['default']
    Toast: typeof import('./src/components/Toast/Toast.vue')['default']
    Toaster: typeof import('./src/components/Toast/Toaster.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserMenuContent: typeof import('./src/components/UserMenuContent.vue')['default']
  }
}
